
name: OMC MSYS2

on:
  workflow_dispatch:
    branches: [ $default-branch, master]
  push:

    branches: [ $default-branch, master]

  pull_request:
    branches:  [ $default-branch, master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git wget zip unzip tar make diffutils patch 
          autoconf automake m4 pkg-config libtool flex bison 
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-opencl-headers
          mingw-w64-x86_64-openblas
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ccache
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-wheel
          mingw-w64-x86_64-dlfcn
          mingw-w64-x86_64-msmpi
          mingw-w64-x86_64-lpsolve
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-expat
          mingw-w64-x86_64-ncurses
          mingw-w64-x86_64-readline
          mingw-w64-x86_64-sundials 
          mingw-w64-x86_64-doxygen
#          mingw-w64-x86_64-zeromq 
#          mingw-w64-x86_64-OpenSceneGraph
#          mingw-w64-x86_64-qt5
#          mingw-w64-x86_64-qtwebkit
#          mingw-w64-x86_64-gc

    - name: Install JAVA
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install oraclejdk
# this previously worked, but not any more...       
#    - name: Install JAVA
#      run: |
#        wget "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.msi"
#        msiexec -i jdk-17_windows-x64_bin.msi -qn -passive
#        export PATH=$PATH:/c/Program\ Files/Java/jdk-17.0.1/bin
#        javac --version

    - uses: actions/checkout@v2
      with:
        submodules: recursive

#    - name: Look at graphstream
#      run: |
#        pushd  OMCompiler/3rdParty/graphstream/gs-netstream/c++/src
#        ls -la
#        echo "--------- netstream-storage.h -----------"
#        cat netstream-storage.h
#        echo "-----------------------------------------"
#        popd
#        pushd OMCompiler/3rdParty/graphstream/
#        wget https://github.com/jdpipe/gs-netstream/archive/refs/heads/master.zip
#        cd gs-netstream
#        bsdtar xvf ../master.zip -s'|[^/]*/||'
#        cd c++/src
#        echo "--------- new netstream-storage.h -----------"
#        cat netstream-storage.h
#        echo "-----------------------------------------"
#        popd

    - name: Check 3rdParty
      run: |
        cd OMCompiler
        echo "LS 3RDPARTY----------"
        ls 3rdParty
        echo "---------------------"

    - name: Build OMC
      run: |
        export PATH=$PATH:~/.local/bin
        export PATH=$PATH:/c/Program\ Files/Java/jdk-17.0.1/bin
        export OMDEV=/mingw64
        mkdir build
        cd build
        cmake ../ -Wno-dev -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=$HOME/.local -DOM_ENABLE_GUI_CLIENTS=OFF
        make omc -j2

    - name: Build Whatever Else
      run: |
        cd build
        make -j2

    - name: Install
      run: |
        cd build
        mkdir tempinst
        DESTDIR=tempinst make -j2 install
    
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: omc-installed
        path: build/tempinst

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cmake-logs
        path: build/CMakeFiles/*.log

# vim:sw=2:ts=2:et:tw=80
